[2022-01-25 09:30:31,997] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T09:25:08.446333+00:00 [queued]>
[2022-01-25 09:30:32,023] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T09:25:08.446333+00:00 [queued]>
[2022-01-25 09:30:32,024] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 09:30:32,024] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-01-25 09:30:32,024] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 09:30:32,037] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): apply_model> on 2022-01-25T09:25:08.446333+00:00
[2022-01-25 09:30:32,090] {standard_task_runner.py:52} INFO - Started process 48 to run task
[2022-01-25 09:30:32,100] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'apply_model', '2022-01-25T09:25:08.446333+00:00', '--job-id', '15', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmpqtzgqtnq', '--error-file', '/tmp/tmpytd07sna']
[2022-01-25 09:30:32,107] {standard_task_runner.py:77} INFO - Job 15: Subtask apply_model
[2022-01-25 09:30:32,183] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.apply_model 2022-01-25T09:25:08.446333+00:00 [running]> on host e28fac53771a
[2022-01-25 09:30:32,229] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=apply_model
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T09:25:08.446333+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T09:25:08.446333+00:00
[2022-01-25 09:30:39,406] {python.py:118} INFO - Done. Returned value was: None
[2022-01-25 09:30:39,418] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=classification, task_id=apply_model, execution_date=20220125T092508, start_date=20220125T093032, end_date=20220125T093039
[2022-01-25 09:30:39,456] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-25 09:30:39,481] {local_task_job.py:146} INFO - Task exited with return code 0
