[2022-01-26 04:16:32,183] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.check_data_exist 2022-01-25T00:00:00+00:00 [queued]>
[2022-01-26 04:16:32,270] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.check_data_exist 2022-01-25T00:00:00+00:00 [queued]>
[2022-01-26 04:16:32,350] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 04:16:32,361] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-01-26 04:16:32,364] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 04:16:32,403] {taskinstance.py:1063} INFO - Executing <Task(BranchPythonOperator): check_data_exist> on 2022-01-25T00:00:00+00:00
[2022-01-26 04:16:32,413] {standard_task_runner.py:52} INFO - Started process 39 to run task
[2022-01-26 04:16:32,429] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'check_data_exist', '2022-01-25T00:00:00+00:00', '--job-id', '192', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmp0o09vfw0', '--error-file', '/tmp/tmpe8nx1we7']
[2022-01-26 04:16:32,441] {standard_task_runner.py:77} INFO - Job 192: Subtask check_data_exist
[2022-01-26 04:16:32,599] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.check_data_exist 2022-01-25T00:00:00+00:00 [running]> on host 115f9a25dda0
[2022-01-26 04:16:32,742] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=check_data_exist
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T00:00:00+00:00
[2022-01-26 04:16:32,831] {python.py:118} INFO - Done. Returned value was: end
[2022-01-26 04:16:32,833] {skipmixin.py:124} INFO - Following branch end
[2022-01-26 04:16:32,858] {skipmixin.py:155} INFO - Skipping tasks ['load_data']
[2022-01-26 04:16:33,125] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=classification, task_id=check_data_exist, execution_date=20220125T000000, start_date=20220126T041632, end_date=20220126T041633
[2022-01-26 04:16:33,264] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-26 04:16:33,324] {local_task_job.py:146} INFO - Task exited with return code 0
