[2022-01-25 09:35:50,184] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T09:30:08.446333+00:00 [queued]>
[2022-01-25 09:35:50,210] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T09:30:08.446333+00:00 [queued]>
[2022-01-25 09:35:50,211] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 09:35:50,211] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-01-25 09:35:50,212] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 09:35:50,225] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): apply_model> on 2022-01-25T09:30:08.446333+00:00
[2022-01-25 09:35:50,234] {standard_task_runner.py:52} INFO - Started process 311 to run task
[2022-01-25 09:35:50,241] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'apply_model', '2022-01-25T09:30:08.446333+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmpcro0wlhd', '--error-file', '/tmp/tmpuhqdbc0k']
[2022-01-25 09:35:50,248] {standard_task_runner.py:77} INFO - Job 21: Subtask apply_model
[2022-01-25 09:35:50,331] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.apply_model 2022-01-25T09:30:08.446333+00:00 [running]> on host e28fac53771a
[2022-01-25 09:35:50,405] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=apply_model
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T09:30:08.446333+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T09:30:08.446333+00:00
[2022-01-25 09:36:12,185] {logging_mixin.py:104} WARNING - /usr/local/lib/python3.6/site-packages/PIL/Image.py:976 UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
[2022-01-25 09:36:24,544] {python.py:118} INFO - Done. Returned value was: None
[2022-01-25 09:36:24,564] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=classification, task_id=apply_model, execution_date=20220125T093008, start_date=20220125T093550, end_date=20220125T093624
[2022-01-25 09:36:24,619] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-25 09:36:24,661] {local_task_job.py:146} INFO - Task exited with return code 0
