[2022-01-25 09:30:26,373] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.load_data 2022-01-25T09:25:08.446333+00:00 [queued]>
[2022-01-25 09:30:26,396] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.load_data 2022-01-25T09:25:08.446333+00:00 [queued]>
[2022-01-25 09:30:26,397] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 09:30:26,397] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-01-25 09:30:26,398] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 09:30:26,410] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): load_data> on 2022-01-25T09:25:08.446333+00:00
[2022-01-25 09:30:26,415] {standard_task_runner.py:52} INFO - Started process 46 to run task
[2022-01-25 09:30:26,420] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'load_data', '2022-01-25T09:25:08.446333+00:00', '--job-id', '14', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmp59wgih1g', '--error-file', '/tmp/tmpe8etgtbm']
[2022-01-25 09:30:26,425] {standard_task_runner.py:77} INFO - Job 14: Subtask load_data
[2022-01-25 09:30:26,474] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.load_data 2022-01-25T09:25:08.446333+00:00 [running]> on host e28fac53771a
[2022-01-25 09:30:26,516] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T09:25:08.446333+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T09:25:08.446333+00:00
[2022-01-25 09:30:28,818] {python.py:118} INFO - Done. Returned value was: None
[2022-01-25 09:30:28,832] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=classification, task_id=load_data, execution_date=20220125T092508, start_date=20220125T093026, end_date=20220125T093028
[2022-01-25 09:30:28,867] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-25 09:30:28,902] {local_task_job.py:146} INFO - Task exited with return code 0
